// <auto-generated />
using System;
using GymWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymWebApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119180929_AlterPricePrecision")]
    partial class AlterPricePrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymWebApp.Data.Entities.Abstract.AuditableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<bool>("Removed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("AuditableEntity");

                    b.HasDiscriminator().HasValue("AuditableEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Removed")
                        .HasColumnType("bit");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Removed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.Employment", b =>
                {
                    b.HasBaseType("GymWebApp.Data.Entities.Abstract.AuditableEntity");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasIndex("EmployeeId");

                    b.HasDiscriminator().HasValue("Employment");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.Exercise", b =>
                {
                    b.HasBaseType("GymWebApp.Data.Entities.Abstract.AuditableEntity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MuscleGroup")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<int>("RepetitionsNumber")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("RestTime")
                        .HasColumnType("time");

                    b.Property<int>("SeriesNumber")
                        .HasColumnType("int");

                    b.Property<int>("TrainingPlanSessionId")
                        .HasColumnType("int");

                    b.HasIndex("TrainingPlanSessionId");

                    b.HasDiscriminator().HasValue("Exercise");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.GroupTraining", b =>
                {
                    b.HasBaseType("GymWebApp.Data.Entities.Abstract.AuditableEntity");

                    b.Property<string>("CancellationReason")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("time");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit");

                    b.Property<int>("MaxParticipantNumber")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("int");

                    b.HasIndex("TrainerId");

                    b.HasIndex("TrainingTypeId");

                    b.ToTable("AuditableEntity", t =>
                        {
                            t.Property("Description")
                                .HasColumnName("GroupTraining_Description");
                        });

                    b.HasDiscriminator().HasValue("GroupTraining");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.GroupTrainingParticipation", b =>
                {
                    b.HasBaseType("GymWebApp.Data.Entities.Abstract.AuditableEntity");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("GroupTrainingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasIndex("ClientId");

                    b.HasIndex("GroupTrainingId");

                    b.ToTable("AuditableEntity", t =>
                        {
                            t.Property("CancelledAt")
                                .HasColumnName("GroupTrainingParticipation_CancelledAt");

                            t.Property("IsCancelled")
                                .HasColumnName("GroupTrainingParticipation_IsCancelled");
                        });

                    b.HasDiscriminator().HasValue("GroupTrainingParticipation");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.GymMembership", b =>
                {
                    b.HasBaseType("GymWebApp.Data.Entities.Abstract.AuditableEntity");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<int>("MembershipPlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasIndex("ClientId");

                    b.HasIndex("MembershipPlanId");

                    b.ToTable("AuditableEntity", t =>
                        {
                            t.Property("CancelledAt")
                                .HasColumnName("GymMembership_CancelledAt");

                            t.Property("ClientId")
                                .HasColumnName("GymMembership_ClientId");

                            t.Property("EndDate")
                                .HasColumnName("GymMembership_EndDate");

                            t.Property("IsCancelled")
                                .HasColumnName("GymMembership_IsCancelled");

                            t.Property("StartDate")
                                .HasColumnName("GymMembership_StartDate");
                        });

                    b.HasDiscriminator().HasValue("GymMembership");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.IndividualTraining", b =>
                {
                    b.HasBaseType("GymWebApp.Data.Entities.Abstract.AuditableEntity");

                    b.Property<string>("CancellationReason")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<TimeSpan>("Duration")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("time");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasIndex("ClientId");

                    b.HasIndex("TrainerId");

                    b.ToTable("AuditableEntity", t =>
                        {
                            t.Property("ClientId")
                                .HasColumnName("IndividualTraining_ClientId");

                            t.Property("Description")
                                .HasColumnName("IndividualTraining_Description");

                            t.Property("TrainerId")
                                .HasColumnName("IndividualTraining_TrainerId");
                        });

                    b.HasDiscriminator().HasValue("IndividualTraining");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.MembershipPlan", b =>
                {
                    b.HasBaseType("GymWebApp.Data.Entities.Abstract.AuditableEntity");

                    b.Property<bool>("CanAccessGroupTraining")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAccessPersonalTraining")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReceiveTrainingPlans")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReserveTrainings")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("int");

                    b.Property<string>("DurationTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxTrainingsPerMonth")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("AuditableEntity", t =>
                        {
                            t.Property("Description")
                                .HasColumnName("MembershipPlan_Description");

                            t.Property("IsActive")
                                .HasColumnName("MembershipPlan_IsActive");
                        });

                    b.HasDiscriminator().HasValue("MembershipPlan");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.Payment", b =>
                {
                    b.HasBaseType("GymWebApp.Data.Entities.Abstract.AuditableEntity");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GymMembershipId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("GymMembershipId");

                    b.HasDiscriminator().HasValue("Payment");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.Shift", b =>
                {
                    b.HasBaseType("GymWebApp.Data.Entities.Abstract.AuditableEntity");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AuditableEntity", t =>
                        {
                            t.Property("EmployeeId")
                                .HasColumnName("Shift_EmployeeId");
                        });

                    b.HasDiscriminator().HasValue("Shift");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.TrainingPlan", b =>
                {
                    b.HasBaseType("GymWebApp.Data.Entities.Abstract.AuditableEntity");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasIndex("ClientId");

                    b.HasIndex("TrainerId");

                    b.ToTable("AuditableEntity", t =>
                        {
                            t.Property("ClientId")
                                .HasColumnName("TrainingPlan_ClientId");

                            t.Property("Description")
                                .HasColumnName("TrainingPlan_Description");

                            t.Property("EndDate")
                                .HasColumnName("TrainingPlan_EndDate");

                            t.Property("IsActive")
                                .HasColumnName("TrainingPlan_IsActive");

                            t.Property("Name")
                                .HasColumnName("TrainingPlan_Name");

                            t.Property("StartDate")
                                .HasColumnName("TrainingPlan_StartDate");

                            t.Property("TrainerId")
                                .HasColumnName("TrainingPlan_TrainerId");
                        });

                    b.HasDiscriminator().HasValue("TrainingPlan");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.TrainingPlanSession", b =>
                {
                    b.HasBaseType("GymWebApp.Data.Entities.Abstract.AuditableEntity");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingPlanId")
                        .HasColumnType("int");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("AuditableEntity", t =>
                        {
                            t.Property("Notes")
                                .HasColumnName("TrainingPlanSession_Notes");
                        });

                    b.HasDiscriminator().HasValue("TrainingPlanSession");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.TrainingType", b =>
                {
                    b.HasBaseType("GymWebApp.Data.Entities.Abstract.AuditableEntity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("AuditableEntity", t =>
                        {
                            t.Property("Description")
                                .HasColumnName("TrainingType_Description");

                            t.Property("DifficultyLevel")
                                .HasColumnName("TrainingType_DifficultyLevel");

                            t.Property("IsActive")
                                .HasColumnName("TrainingType_IsActive");

                            t.Property("Name")
                                .HasColumnName("TrainingType_Name");
                        });

                    b.HasDiscriminator().HasValue("TrainingType");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.Abstract.AuditableEntity", b =>
                {
                    b.HasOne("GymWebApp.Data.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymWebApp.Data.Entities.ApplicationUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GymWebApp.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GymWebApp.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymWebApp.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GymWebApp.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.Employment", b =>
                {
                    b.HasOne("GymWebApp.Data.Entities.Employee", "Employee")
                        .WithMany("Employments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.Exercise", b =>
                {
                    b.HasOne("GymWebApp.Data.Entities.TrainingPlanSession", "TrainingPlanSession")
                        .WithMany("Exercises")
                        .HasForeignKey("TrainingPlanSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainingPlanSession");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.GroupTraining", b =>
                {
                    b.HasOne("GymWebApp.Data.Entities.Employee", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymWebApp.Data.Entities.TrainingType", "TrainingType")
                        .WithMany()
                        .HasForeignKey("TrainingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trainer");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.GroupTrainingParticipation", b =>
                {
                    b.HasOne("GymWebApp.Data.Entities.Client", "Client")
                        .WithMany("GroupTrainingsParticipations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymWebApp.Data.Entities.GroupTraining", "GroupTraining")
                        .WithMany("Participations")
                        .HasForeignKey("GroupTrainingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("GroupTraining");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.GymMembership", b =>
                {
                    b.HasOne("GymWebApp.Data.Entities.Client", "Client")
                        .WithMany("GymMemberships")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymWebApp.Data.Entities.MembershipPlan", "MembershipPlan")
                        .WithMany("GymMemberships")
                        .HasForeignKey("MembershipPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("MembershipPlan");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.IndividualTraining", b =>
                {
                    b.HasOne("GymWebApp.Data.Entities.Client", "Client")
                        .WithMany("IndividualTrainings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GymWebApp.Data.Entities.Employee", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.Payment", b =>
                {
                    b.HasOne("GymWebApp.Data.Entities.GymMembership", "GymMembership")
                        .WithMany("Payments")
                        .HasForeignKey("GymMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GymMembership");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.Shift", b =>
                {
                    b.HasOne("GymWebApp.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.TrainingPlan", b =>
                {
                    b.HasOne("GymWebApp.Data.Entities.Client", "Client")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymWebApp.Data.Entities.Employee", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.TrainingPlanSession", b =>
                {
                    b.HasOne("GymWebApp.Data.Entities.TrainingPlan", "TrainingPlan")
                        .WithMany("Sessions")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.Client", b =>
                {
                    b.Navigation("GroupTrainingsParticipations");

                    b.Navigation("GymMemberships");

                    b.Navigation("IndividualTrainings");

                    b.Navigation("TrainingPlans");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.Employee", b =>
                {
                    b.Navigation("Employments");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.GroupTraining", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.GymMembership", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.MembershipPlan", b =>
                {
                    b.Navigation("GymMemberships");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.TrainingPlan", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("GymWebApp.Data.Entities.TrainingPlanSession", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
